services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=joboffers'
      - 'POSTGRES_PASSWORD=joboffers'
      - 'POSTGRES_USER=joboffers'
    ports:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
